name: Ubuntu

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  workflow_dispatch:
  release:
    types:
      - released

jobs:
  ci:
    name: ${{ matrix.distro }}
    runs-on: ubuntu-latest    
    strategy:
      fail-fast: false
      matrix:
        distro: [foxy, humble, jazzy]
    container: ros:${{ matrix.distro }}
    env:
      CCACHE_DIR: ${{ github.workspace }}/${{ matrix.distro }}/.ccache
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/UTC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: target_ws/src

      - name: Build and test
        uses: tesseract-robotics/colcon-action@v11
        with:
          before-script: source /opt/ros/${{ matrix.distro }}/setup.bash
          ccache-prefix: ${{ matrix.distro }}
          add-ros-ppa: false
          vcs-file: dependencies.repos
          target-path: target_ws/src
          target-args: --cmake-args -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=ON -DENABLE_RUN_TESTING=OFF
